package com.sistemabancario.model.pojo;
// Generated 18/07/2017 15:29:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Planilla generated by hbm2java
 */
public class Planilla  implements java.io.Serializable {


     private String idplanilla;
     private Servicio servicio;
     private Transaccion transaccion;
     private Double valor;
     private String idContratoCliente;
     private Date fechaEmision;
     private Date fechaPago;
     private String estado;

    public Planilla() {
    }

	
    public Planilla(String idplanilla, Servicio servicio, Transaccion transaccion) {
        this.idplanilla = idplanilla;
        this.servicio = servicio;
        this.transaccion = transaccion;
    }
    public Planilla(String idplanilla, Servicio servicio, Transaccion transaccion, Double valor, String idContratoCliente, Date fechaEmision, Date fechaPago, String estado) {
       this.idplanilla = idplanilla;
       this.servicio = servicio;
       this.transaccion = transaccion;
       this.valor = valor;
       this.idContratoCliente = idContratoCliente;
       this.fechaEmision = fechaEmision;
       this.fechaPago = fechaPago;
       this.estado = estado;
    }
   
    public String getIdplanilla() {
        return this.idplanilla;
    }
    
    public void setIdplanilla(String idplanilla) {
        this.idplanilla = idplanilla;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Transaccion getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Transaccion transaccion) {
        this.transaccion = transaccion;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public String getIdContratoCliente() {
        return this.idContratoCliente;
    }
    
    public void setIdContratoCliente(String idContratoCliente) {
        this.idContratoCliente = idContratoCliente;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


