package com.sistemabancario.model.pojo;
// Generated 18/07/2017 16:11:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name="telefono"
    ,catalog="bancodb"
)
public class Telefono  implements java.io.Serializable {


     private Integer idtelefono;
     private PropietarioCuenta propietarioCuenta;
     private String numero;

    public Telefono() {
    }

	
    public Telefono(PropietarioCuenta propietarioCuenta) {
        this.propietarioCuenta = propietarioCuenta;
    }
    public Telefono(PropietarioCuenta propietarioCuenta, String numero) {
       this.propietarioCuenta = propietarioCuenta;
       this.numero = numero;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtelefono", unique=true, nullable=false)
    public Integer getIdtelefono() {
        return this.idtelefono;
    }
    
    public void setIdtelefono(Integer idtelefono) {
        this.idtelefono = idtelefono;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="propietario_cuenta_idusuario", nullable=false)
    public PropietarioCuenta getPropietarioCuenta() {
        return this.propietarioCuenta;
    }
    
    public void setPropietarioCuenta(PropietarioCuenta propietarioCuenta) {
        this.propietarioCuenta = propietarioCuenta;
    }

    
    @Column(name="numero", length=45)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }




}


