package com.sistemabancario.model.pojo;
// Generated 18/07/2017 15:29:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoTransaccion generated by hbm2java
 */
public class TipoTransaccion  implements java.io.Serializable {


     private Integer idtipoTransaccion;
     private String nombre;
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

    public TipoTransaccion() {
    }

    public TipoTransaccion(String nombre, Set<Transaccion> transaccions) {
       this.nombre = nombre;
       this.transaccions = transaccions;
    }
   
    public Integer getIdtipoTransaccion() {
        return this.idtipoTransaccion;
    }
    
    public void setIdtipoTransaccion(Integer idtipoTransaccion) {
        this.idtipoTransaccion = idtipoTransaccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }




}


