package com.sistemabancario.model.pojo;
// Generated 18/07/2017 15:29:45 by Hibernate Tools 4.3.1



/**
 * TransferenciaHasCuenta generated by hbm2java
 */
public class TransferenciaHasCuenta  implements java.io.Serializable {


     private TransferenciaHasCuentaId id;
     private Cuenta cuenta;
     private String idCuentaBeneficiario;

    public TransferenciaHasCuenta() {
    }

	
    public TransferenciaHasCuenta(TransferenciaHasCuentaId id, Cuenta cuenta) {
        this.id = id;
        this.cuenta = cuenta;
    }
    public TransferenciaHasCuenta(TransferenciaHasCuentaId id, Cuenta cuenta, String idCuentaBeneficiario) {
       this.id = id;
       this.cuenta = cuenta;
       this.idCuentaBeneficiario = idCuentaBeneficiario;
    }
   
    public TransferenciaHasCuentaId getId() {
        return this.id;
    }
    
    public void setId(TransferenciaHasCuentaId id) {
        this.id = id;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public String getIdCuentaBeneficiario() {
        return this.idCuentaBeneficiario;
    }
    
    public void setIdCuentaBeneficiario(String idCuentaBeneficiario) {
        this.idCuentaBeneficiario = idCuentaBeneficiario;
    }




}


