package com.sistemabancario.model.pojo;
// Generated 18/07/2017 15:29:45 by Hibernate Tools 4.3.1



/**
 * TransferenciaHasCuentaId generated by hbm2java
 */
public class TransferenciaHasCuentaId  implements java.io.Serializable {


     private String transferenciaIdtransferencia;
     private String cuentaIdcuenta;

    public TransferenciaHasCuentaId() {
    }

    public TransferenciaHasCuentaId(String transferenciaIdtransferencia, String cuentaIdcuenta) {
       this.transferenciaIdtransferencia = transferenciaIdtransferencia;
       this.cuentaIdcuenta = cuentaIdcuenta;
    }
   
    public String getTransferenciaIdtransferencia() {
        return this.transferenciaIdtransferencia;
    }
    
    public void setTransferenciaIdtransferencia(String transferenciaIdtransferencia) {
        this.transferenciaIdtransferencia = transferenciaIdtransferencia;
    }
    public String getCuentaIdcuenta() {
        return this.cuentaIdcuenta;
    }
    
    public void setCuentaIdcuenta(String cuentaIdcuenta) {
        this.cuentaIdcuenta = cuentaIdcuenta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TransferenciaHasCuentaId) ) return false;
		 TransferenciaHasCuentaId castOther = ( TransferenciaHasCuentaId ) other; 
         
		 return ( (this.getTransferenciaIdtransferencia()==castOther.getTransferenciaIdtransferencia()) || ( this.getTransferenciaIdtransferencia()!=null && castOther.getTransferenciaIdtransferencia()!=null && this.getTransferenciaIdtransferencia().equals(castOther.getTransferenciaIdtransferencia()) ) )
 && ( (this.getCuentaIdcuenta()==castOther.getCuentaIdcuenta()) || ( this.getCuentaIdcuenta()!=null && castOther.getCuentaIdcuenta()!=null && this.getCuentaIdcuenta().equals(castOther.getCuentaIdcuenta()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTransferenciaIdtransferencia() == null ? 0 : this.getTransferenciaIdtransferencia().hashCode() );
         result = 37 * result + ( getCuentaIdcuenta() == null ? 0 : this.getCuentaIdcuenta().hashCode() );
         return result;
   }   


}


