package com.sistema_bancario.model.pojo;
// Generated 21/07/2017 14:57:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name="email"
    ,catalog="bancodb"
)
public class Email  implements java.io.Serializable {


     private Integer idemail;
     private String email;
     private Set<PropietarioCuenta> propietarioCuentas = new HashSet<PropietarioCuenta>(0);
     private Set<PropietarioCuenta> propietarioCuentas_1 = new HashSet<PropietarioCuenta>(0);

    public Email() {
    }

    public Email(String email, Set<PropietarioCuenta> propietarioCuentas, Set<PropietarioCuenta> propietarioCuentas_1) {
       this.email = email;
       this.propietarioCuentas = propietarioCuentas;
       this.propietarioCuentas_1 = propietarioCuentas_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idemail", unique=true, nullable=false)
    public Integer getIdemail() {
        return this.idemail;
    }
    
    public void setIdemail(Integer idemail) {
        this.idemail = idemail;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="propietario_cuenta_has_email", catalog="bancodb", joinColumns = { 
        @JoinColumn(name="email_idemail", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="propietario_cuenta_idusuario", nullable=false, updatable=false) })
    public Set<PropietarioCuenta> getPropietarioCuentas() {
        return this.propietarioCuentas;
    }
    
    public void setPropietarioCuentas(Set<PropietarioCuenta> propietarioCuentas) {
        this.propietarioCuentas = propietarioCuentas;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="usuario_has_email", catalog="bancodb", joinColumns = { 
        @JoinColumn(name="email_idemail", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="usuario_idusuario", nullable=false, updatable=false) })
    public Set<PropietarioCuenta> getPropietarioCuentas_1() {
        return this.propietarioCuentas_1;
    }
    
    public void setPropietarioCuentas_1(Set<PropietarioCuenta> propietarioCuentas_1) {
        this.propietarioCuentas_1 = propietarioCuentas_1;
    }




}


