package com.sistema_bancario.model.pojo;
// Generated 21/07/2017 14:57:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name="telefono"
    ,catalog="bancodb"
)
public class Telefono  implements java.io.Serializable {


     private Integer idtelefono;
     private String numero;
     private Set<PropietarioCuenta> propietarioCuentas = new HashSet<PropietarioCuenta>(0);

    public Telefono() {
    }

    public Telefono(String numero, Set<PropietarioCuenta> propietarioCuentas) {
       this.numero = numero;
       this.propietarioCuentas = propietarioCuentas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtelefono", unique=true, nullable=false)
    public Integer getIdtelefono() {
        return this.idtelefono;
    }
    
    public void setIdtelefono(Integer idtelefono) {
        this.idtelefono = idtelefono;
    }

    
    @Column(name="numero", length=45)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="propietario_cuenta_has_telefono", catalog="bancodb", joinColumns = { 
        @JoinColumn(name="telefono_idtelefono", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="propietario_cuenta_idusuario", nullable=false, updatable=false) })
    public Set<PropietarioCuenta> getPropietarioCuentas() {
        return this.propietarioCuentas;
    }
    
    public void setPropietarioCuentas(Set<PropietarioCuenta> propietarioCuentas) {
        this.propietarioCuentas = propietarioCuentas;
    }




}


