package com.sistema_bancario.model.pojo;
// Generated 21/07/2017 14:57:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoCuenta generated by hbm2java
 */
@Entity
@Table(name="tipo_cuenta"
    ,catalog="bancodb"
)
public class TipoCuenta  implements java.io.Serializable {


     private Integer idtipoCuenta;
     private String nombre;
     private Set<Cuenta> cuentas = new HashSet<Cuenta>(0);

    public TipoCuenta() {
    }

    public TipoCuenta(String nombre, Set<Cuenta> cuentas) {
       this.nombre = nombre;
       this.cuentas = cuentas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtipo_cuenta", unique=true, nullable=false)
    public Integer getIdtipoCuenta() {
        return this.idtipoCuenta;
    }
    
    public void setIdtipoCuenta(Integer idtipoCuenta) {
        this.idtipoCuenta = idtipoCuenta;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoCuenta")
    public Set<Cuenta> getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set<Cuenta> cuentas) {
        this.cuentas = cuentas;
    }




}


