package com.model.pojo;
// Generated 18/07/2017 22:58:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name="email"
    ,catalog="bancodb"
)
public class Email  implements java.io.Serializable {


     private Integer idemail;
     private PropietarioCuenta propietarioCuenta;
     private String email;
     private Set<PropietarioCuenta> propietarioCuentas = new HashSet<PropietarioCuenta>(0);

    public Email() {
    }

	
    public Email(PropietarioCuenta propietarioCuenta) {
        this.propietarioCuenta = propietarioCuenta;
    }
    public Email(PropietarioCuenta propietarioCuenta, String email, Set<PropietarioCuenta> propietarioCuentas) {
       this.propietarioCuenta = propietarioCuenta;
       this.email = email;
       this.propietarioCuentas = propietarioCuentas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idemail", unique=true, nullable=false)
    public Integer getIdemail() {
        return this.idemail;
    }
    
    public void setIdemail(Integer idemail) {
        this.idemail = idemail;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="propietario_cuenta_idusuario", nullable=false)
    public PropietarioCuenta getPropietarioCuenta() {
        return this.propietarioCuenta;
    }
    
    public void setPropietarioCuenta(PropietarioCuenta propietarioCuenta) {
        this.propietarioCuenta = propietarioCuenta;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="usuario_has_email", catalog="bancodb", joinColumns = { 
        @JoinColumn(name="email_idemail", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="usuario_idusuario", nullable=false, updatable=false) })
    public Set<PropietarioCuenta> getPropietarioCuentas() {
        return this.propietarioCuentas;
    }
    
    public void setPropietarioCuentas(Set<PropietarioCuenta> propietarioCuentas) {
        this.propietarioCuentas = propietarioCuentas;
    }




}


