package Model;
// Generated 18/07/2017 15:29:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Email generated by hbm2java
 */
public class Email  implements java.io.Serializable {


     private Integer idemail;
     private PropietarioCuenta propietarioCuenta;
     private String email;
     private Set<PropietarioCuenta> propietarioCuentas = new HashSet<PropietarioCuenta>(0);

    public Email() {
    }

	
    public Email(PropietarioCuenta propietarioCuenta) {
        this.propietarioCuenta = propietarioCuenta;
    }
    public Email(PropietarioCuenta propietarioCuenta, String email, Set<PropietarioCuenta> propietarioCuentas) {
       this.propietarioCuenta = propietarioCuenta;
       this.email = email;
       this.propietarioCuentas = propietarioCuentas;
    }
   
    public Integer getIdemail() {
        return this.idemail;
    }
    
    public void setIdemail(Integer idemail) {
        this.idemail = idemail;
    }
    public PropietarioCuenta getPropietarioCuenta() {
        return this.propietarioCuenta;
    }
    
    public void setPropietarioCuenta(PropietarioCuenta propietarioCuenta) {
        this.propietarioCuenta = propietarioCuenta;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<PropietarioCuenta> getPropietarioCuentas() {
        return this.propietarioCuentas;
    }
    
    public void setPropietarioCuentas(Set<PropietarioCuenta> propietarioCuentas) {
        this.propietarioCuentas = propietarioCuentas;
    }




}


