package Model;
// Generated 18/07/2017 15:29:45 by Hibernate Tools 4.3.1



/**
 * Telefono generated by hbm2java
 */
public class Telefono  implements java.io.Serializable {


     private Integer idtelefono;
     private PropietarioCuenta propietarioCuenta;
     private String numero;

    public Telefono() {
    }

	
    public Telefono(PropietarioCuenta propietarioCuenta) {
        this.propietarioCuenta = propietarioCuenta;
    }
    public Telefono(PropietarioCuenta propietarioCuenta, String numero) {
       this.propietarioCuenta = propietarioCuenta;
       this.numero = numero;
    }
   
    public Integer getIdtelefono() {
        return this.idtelefono;
    }
    
    public void setIdtelefono(Integer idtelefono) {
        this.idtelefono = idtelefono;
    }
    public PropietarioCuenta getPropietarioCuenta() {
        return this.propietarioCuenta;
    }
    
    public void setPropietarioCuenta(PropietarioCuenta propietarioCuenta) {
        this.propietarioCuenta = propietarioCuenta;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }




}


