package Model;
// Generated 18/07/2017 15:29:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoServicio generated by hbm2java
 */
public class TipoServicio  implements java.io.Serializable {


     private int idtipoServicio;
     private String nombre;
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public TipoServicio() {
    }

	
    public TipoServicio(int idtipoServicio) {
        this.idtipoServicio = idtipoServicio;
    }
    public TipoServicio(int idtipoServicio, String nombre, Set<Servicio> servicios) {
       this.idtipoServicio = idtipoServicio;
       this.nombre = nombre;
       this.servicios = servicios;
    }
   
    public int getIdtipoServicio() {
        return this.idtipoServicio;
    }
    
    public void setIdtipoServicio(int idtipoServicio) {
        this.idtipoServicio = idtipoServicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


