package Model;
// Generated 18/07/2017 15:29:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoCuenta generated by hbm2java
 */
public class TipoCuenta  implements java.io.Serializable {


     private Integer idtipoCuenta;
     private String nombre;
     private Set<Cuenta> cuentas = new HashSet<Cuenta>(0);

    public TipoCuenta() {
    }

    public TipoCuenta(String nombre, Set<Cuenta> cuentas) {
       this.nombre = nombre;
       this.cuentas = cuentas;
    }
   
    public Integer getIdtipoCuenta() {
        return this.idtipoCuenta;
    }
    
    public void setIdtipoCuenta(Integer idtipoCuenta) {
        this.idtipoCuenta = idtipoCuenta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Cuenta> getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set<Cuenta> cuentas) {
        this.cuentas = cuentas;
    }




}


