<<<<<<< HEAD:SistemaBancario/src/main/java/com/sistemabancario/model/pojo/TipoTransaccion.java
package com.sistemabancario.model.pojo;
// Generated 18/07/2017 16:11:11 by Hibernate Tools 4.3.1
=======
package Model;
// Generated 18/07/2017 15:29:45 by Hibernate Tools 4.3.1
>>>>>>> 218c09201e8e3c382f722ec23e62754416b08f1d:SistemaBancario/src/main/java/Model/TipoTransaccion.java


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoTransaccion generated by hbm2java
 */
@Entity
@Table(name="tipo_transaccion"
    ,catalog="bancodb"
)
public class TipoTransaccion  implements java.io.Serializable {


     private Integer idtipoTransaccion;
     private String nombre;
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

    public TipoTransaccion() {
    }

    public TipoTransaccion(String nombre, Set<Transaccion> transaccions) {
       this.nombre = nombre;
       this.transaccions = transaccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtipo_transaccion", unique=true, nullable=false)
    public Integer getIdtipoTransaccion() {
        return this.idtipoTransaccion;
    }
    
    public void setIdtipoTransaccion(Integer idtipoTransaccion) {
        this.idtipoTransaccion = idtipoTransaccion;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoTransaccion")
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }




}


