package Model;
// Generated 18/07/2017 15:29:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion  implements java.io.Serializable {


     private String idtransaccion;
     private Cuenta cuentaByCuentaIdcuenta2;
     private Cuenta cuentaByCuentaIdcuentaPrincipal;
     private TipoTransaccion tipoTransaccion;
     private double cantidad;
     private Date fecha;
     private Set<Planilla> planillas = new HashSet<Planilla>(0);

    public Transaccion() {
    }

	
    public Transaccion(String idtransaccion, Cuenta cuentaByCuentaIdcuenta2, Cuenta cuentaByCuentaIdcuentaPrincipal, TipoTransaccion tipoTransaccion, double cantidad, Date fecha) {
        this.idtransaccion = idtransaccion;
        this.cuentaByCuentaIdcuenta2 = cuentaByCuentaIdcuenta2;
        this.cuentaByCuentaIdcuentaPrincipal = cuentaByCuentaIdcuentaPrincipal;
        this.tipoTransaccion = tipoTransaccion;
        this.cantidad = cantidad;
        this.fecha = fecha;
    }
    public Transaccion(String idtransaccion, Cuenta cuentaByCuentaIdcuenta2, Cuenta cuentaByCuentaIdcuentaPrincipal, TipoTransaccion tipoTransaccion, double cantidad, Date fecha, Set<Planilla> planillas) {
       this.idtransaccion = idtransaccion;
       this.cuentaByCuentaIdcuenta2 = cuentaByCuentaIdcuenta2;
       this.cuentaByCuentaIdcuentaPrincipal = cuentaByCuentaIdcuentaPrincipal;
       this.tipoTransaccion = tipoTransaccion;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.planillas = planillas;
    }
   
    public String getIdtransaccion() {
        return this.idtransaccion;
    }
    
    public void setIdtransaccion(String idtransaccion) {
        this.idtransaccion = idtransaccion;
    }
    public Cuenta getCuentaByCuentaIdcuenta2() {
        return this.cuentaByCuentaIdcuenta2;
    }
    
    public void setCuentaByCuentaIdcuenta2(Cuenta cuentaByCuentaIdcuenta2) {
        this.cuentaByCuentaIdcuenta2 = cuentaByCuentaIdcuenta2;
    }
    public Cuenta getCuentaByCuentaIdcuentaPrincipal() {
        return this.cuentaByCuentaIdcuentaPrincipal;
    }
    
    public void setCuentaByCuentaIdcuentaPrincipal(Cuenta cuentaByCuentaIdcuentaPrincipal) {
        this.cuentaByCuentaIdcuentaPrincipal = cuentaByCuentaIdcuentaPrincipal;
    }
    public TipoTransaccion getTipoTransaccion() {
        return this.tipoTransaccion;
    }
    
    public void setTipoTransaccion(TipoTransaccion tipoTransaccion) {
        this.tipoTransaccion = tipoTransaccion;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Planilla> getPlanillas() {
        return this.planillas;
    }
    
    public void setPlanillas(Set<Planilla> planillas) {
        this.planillas = planillas;
    }




}


